### ISSUE TITLE
图片信息无法显示

### ISSUE THREAD

**Issue by glkwhr** [TRPGEngine/Client#171]
图片上传成功后在输入框中无法显示；发送出去后在聊天记录中依然无法显示：

![img_not_load](https://user-images.githubusercontent.com/4232536/120232282-1bfca080-c208-11eb-88b0-3ac6a1b0340e.png)

获取图片的请求失败：

```
Request URL: https://images.weserv.nl/?url=https://img03.sogoucdn.com/app/a/100520146/ebe6ae3f7729f15f2e55c0e53b311ee8
Request Method: GET
Status Code: 404 
Remote Address: 104.21.79.95:443
Referrer Policy: strict-origin-when-cross-origin
```

尝试浏览器直接访问[URL](https://images.weserv.nl/?url=https://img03.sogoucdn.com/app/a/100520146/ebe6ae3f7729f15f2e55c0e53b311ee8)，response如下：
```
{"status":"error","code":404,"message":"The hostname of the origin is unresolvable (DNS) or blocked by policy."}
```

试着直接访问sogoucdn的连接（https://img03.sogoucdn.com/app/a/100520146/ebe6ae3f7729f15f2e55c0e53b311ee8）：
![image](https://user-images.githubusercontent.com/4232536/120232789-23707980-c209-11eb-930b-6c8fdc1b753e.png)

人工忽略警告后可以获取图片：
![image](https://user-images.githubusercontent.com/4232536/120232870-5155be00-c209-11eb-8b82-d22e88990070.png)

**Comment by moonrailgun** [comment]
这是因为为了成本考虑

将服务聊天图片通过自设图床代理转发到公共图床实现的图片服务。有一定不稳定的情况。

后续我会增加可以改为使用自定义图床的配置

**Comment by glkwhr** [comment]
> 这是因为为了成本考虑
> 
> 将服务聊天图片通过自设图床代理转发到公共图床实现的图片服务。有一定不稳定的情况。
> 
> 后续我会增加可以改为使用自定义图床的配置

请问下不稳定的情况是指使用的公共图床有一定概率会被屏蔽吗？有点好奇这是普遍存在（指与用户环境无关）的情况还是说只在某些条件下会触发造成影响？

这么问因为看起来问题是 https://images.weserv.nl （以及chrome）把 https://img03.sogoucdn.com 认定为危险站点屏蔽了。如果所有用户都是通过这样的方式获取图片的话按说所有用户都应该会遇到这个问题？但实际看来似乎不是特别普遍的情况？

顺带一提，头像的显示没有任何问题。不过估计是因为头像存在数据库中？

那么有什么临时解决的办法吗？类似网址白名单之类的？

**Comment by moonrailgun** [comment]
> 请问下不稳定的情况是指使用的公共图床有一定概率会被屏蔽吗？有点好奇这是普遍存在（指与用户环境无关）的情况还是说只在某些条件下会触发造成影响？

最近可能有点问题，没有本地存储稳定

另外我重新看了一下代码，如果本地没有配置图片转发服务的话是发不了图片的。

总之我回头会增加聊天图片上传到本地或者云的功能

> 顺带一提，头像的显示没有任何问题。不过估计是因为头像存在数据库中？

头像没有问题是因为头像这些数据比较重要，会好好存在本地或者云上，类似的还有笔记系统中的图片

**Comment by glkwhr** [comment]
> 另外我重新看了一下代码，如果本地没有配置图片转发服务的话是发不了图片的。

抱歉之前没说清楚，这个不是我本地测试的结果。是我用https://trpg.moonrailgun.com/时候出现的问题。

**Comment by moonrailgun** [comment]
> > 另外我重新看了一下代码，如果本地没有配置图片转发服务的话是发不了图片的。
> 
> 抱歉之前没说清楚，这个不是我本地测试的结果。是我用[https://trpg.moonrailgun.com/时候出现的问题。](https://trpg.moonrailgun.com/%E6%97%B6%E5%80%99%E5%87%BA%E7%8E%B0%E7%9A%84%E9%97%AE%E9%A2%98%E3%80%82)

我知道，我的意思是有两个问题:

- 第一个是搜狗图床出现的问题
- 另一个是一些细节没有考虑到本地部署，如果本地部署的话没有办法进行聊天图片的上传

两个问题的解决方案都是弃用公用图床改用自己的空间来管理图片

**Comment by glkwhr** [comment]
> > > 另外我重新看了一下代码，如果本地没有配置图片转发服务的话是发不了图片的。
> 
> > 
> 
> > 抱歉之前没说清楚，这个不是我本地测试的结果。是我用[https://trpg.moonrailgun.com/时候出现的问题。](https://trpg.moonrailgun.com/%E6%97%B6%E5%80%99%E5%87%BA%E7%8E%B0%E7%9A%84%E9%97%AE%E9%A2%98%E3%80%82)
> 
> 
> 
> 我知道，我的意思是有两个问题:
> 
> 
> 
> - 第一个是搜狗图床出现的问题
> 
> - 另一个是一些细节没有考虑到本地部署，如果本地部署的话没有办法进行聊天图片的上传
> 
> 
> 
> 两个问题的解决方案都是弃用公用图床改用自己的空间来管理图片

了解了，多谢讲解！

**Comment by moonrailgun** [comment]
修改聊天图片上传逻辑修改为私有存储
https://github.com/TRPGEngine/Client/commit/c24d0f7910bc850ab0ae2b9fc736cd9f8fc40133

**Comment by glkwhr** [comment]
> 修改聊天图片上传逻辑修改为私有存储
> [c24d0f7](https://github.com/TRPGEngine/Client/commit/c24d0f7910bc850ab0ae2b9fc736cd9f8fc40133)

经本地测试已经可以正常上传和显示图片
