### ISSUE TITLE
修改一下创建人物卡的界面

### ISSUE THREAD

**Issue by moonrailgun** [TRPGEngine/Client#179]
创建人物卡界面左边的从`人物库里创建`具有迷惑性。

导致让人想不到需要搜索模板

**Comment by glkwhr** [comment]
初步想法：微调了下布局和文本，大致如下，你觉得如何？
![image](https://user-images.githubusercontent.com/4232536/121461265-5df1b900-c963-11eb-9994-92596414aae0.png)

不过我个人觉得`从人物库里创建`这个按钮放在这个卡片外面可能更合适。因为上面进度条/时间轴的1 2 3布与其并无关联，按钮的作用更多是“导入（Fork）角色卡到玩家自己的角色库”。我觉得类似以下的这类调整可能会更明确些?

1. 把这个按钮单独拿出来作为`复制（或fork）现有角色卡`的按钮与`（从模板）创建角色`按钮并列。
2. 或者在点击`创建角色`按钮后先让玩家选择`复制现有角色卡`还是`从模板开始创建`（可以是个popover或者下拉菜单之类的？），如果选择后者再进入有进度条/时间轴的卡片。

**Comment by glkwhr** [comment]
顺带问一下如果要改文本的话，`translation.json`里的对应key value pair是要手动改吗？

**Comment by moonrailgun** [comment]
Hi @glkwhr , 首先感谢你的建议

我觉得可以设计成参考discord创建群组的形式:
![image](https://user-images.githubusercontent.com/6964737/121470806-4a8d2f00-c9f1-11eb-80c9-9941dc78266c.png)

即引导用户选择三种方式之一: 搜索私人模板, 选择推荐模板, 或者从现有人物卡创建。

之前做的设计并不好，想改掉。

> 顺带问一下如果要改文本的话，translation.json里的对应key value pair是要手动改吗？

TRPG Engine的i18n解决方案是这样的
1. 直接在代码中键入以`t('xxxxx')`这种形式的字符串
2. 执行`yarn run translation:scan`自动更新翻译文件
3. 在除中文以外的语言文件中修改为对应的语言
4. (可选) 执行`yarn run translation:build`收集主项目和插件项目的翻译，生成到`dist`目录

**Comment by glkwhr** [comment]
> Hi @glkwhr , 首先感谢你的建议
> 
> 
> 
> 我觉得可以设计成参考discord创建群组的形式:
> 
> ![image](https://user-images.githubusercontent.com/6964737/121470806-4a8d2f00-c9f1-11eb-80c9-9941dc78266c.png)
> 
> 
> 
> 即引导用户选择三种方式之一: 搜索私人模板, 选择推荐模板, 或者从现有人物卡创建。
> 
> 
> 
> 之前做的设计并不好，想改掉。
> 

这样确实感觉应该会清晰很多，可以的话我会试着找这样的效果来修改。


> > 顺带问一下如果要改文本的话，translation.json里的对应key value pair是要手动改吗？
> 
> 
> 
> TRPG Engine的i18n解决方案是这样的
> 
> 1. 直接在代码中键入以`t('xxxxx')`这种形式的字符串
> 
> 2. 执行`yarn run translation:scan`自动更新翻译文件
> 
> 3. 在除中文以外的语言文件中修改为对应的语言
> 
> 4. (可选) 执行`yarn run translation:build`收集主项目和插件项目的翻译，生成到`dist`目录

了解了，多谢说明！

**Comment by glkwhr** [comment]
https://github.com/TRPGEngine/Client/pull/206

最近工作上事情有点多，鸽了有点久
